spring:
  datasource:
    url: jdbc:mysql://101.201.101.206:3306/workflows?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
    # 自动部署验证设置:true-开启（默认）、false-关闭
    check-process-definitions: false
    #自动部署文件路径后缀
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
#   process-definition-location-prefix: classpath:/processes/
#   process-definition-location-suffixes:
#      - **.bpmn
#      - **.bpmn20.xml
server:
  port: 8085
# pageHelper配置
# 指定数据库
pagehelper:
  helper-dialect: mysql
  # 页码<=0 查询第一页，页码>=总页数查询最后一页
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数
  support-methods-arguments: true


